### PR TITLE
Fuzzer improvements

### LINKED ISSUE #539: Fuzzer improvements
## Make lines empty
```py
try:
    items = list(input().split())
except ...:
    ...
do_something(items[0])
```
This sort of pattern fails when line is unexpectedly empty.

## Append garbage at the end of the output
Judges should take this as a wrong answer, but most judges just forget to check this.

### PR DESCRIPTION
**Pull request by 5K1PY**
Fixes #539

### CODE REVIEW

File: fixtures/sum_kasiopea/judge_bad.cpp [hunk 1]
```diff
@@ -26,19 +25,18 @@ int main(int argc, char** argv) {
...
-        }
+        if (c != contestant + 1)
+            verdict(false, "Wrong answer");
 	}
 
-    fprintf(stderr, "Correct answer");
-	return 42;
+	char trailing;
+	if (scanf(" %c", &trailing) == 1)
+        verdict(false, "Wrong answer");
```
Comment (SvizelPritula) [inline fixtures/sum_kasiopea/judge_bad.cpp]: Shouldn't this line be more indented?
